#
#	Command & Conquer Red Alert(tm)
#	Copyright 2025 Electronic Arts Inc.
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

.nocheck

ALL:	thipx32.dll &
	thipx16.dll

thipx32.dll: thipx.thk thipx32c.cpp thmap32.asm thipx32.lnk
	thunk Thipx.thk
	rem fixthunk
	wpp386 -i$(%WATCOM)\H\NT -i$(%WATCOM)\H -s -mf -3s -bt=nt -bd -zu -4 thipx32c.cpp
	$(%MASM)\ml /DIS_32 /Zf /Fl /c /W3 /Fothipx32a.obj thipx.asm
	$(%MASM)\ml /c /W3 thmap32.asm
	wlink @thipx32.lnk
	wlib -c -n wwipx32.lib +thipx32.dll


thipx16.dll: thipx.thk thipx16a.asm thipx16c.cpp thmap16.asm thipx16.lnk
	thunk Thipx.thk
	wpp -i$(%WATCOM)\H -ml -bd -zu -bt=windows -0 thipx16c.cpp
	$(%MASM)\ml /c /W3 ipx16a.asm
	$(%MASM)\ml /DIS_16 /c /W3 /Fothipx16a.obj thipx.asm
	$(%MASM)\ml /c /W3 thmap16.asm
	wlink @thipx16.lnk
	rc -40 thipx16.dll
	call setinc2.bat


#############################################################################
# This creates the linker command file.
thipx32.lnk : makefile
	%create $^@
	%append $^@ debug all
	%append $^@ system win95 dll initinstance terminstance
	%append $^@ option map
	%append $^@ option caseexact
	%append $^@ option manglednames
	%append $^@ file thipx32a.obj
	%append $^@ file thipx32c.obj
	%append $^@ file thmap32.obj
	%append $^@ library thunk32.lib
	%append $^@ name thipx32.dll
	%append $^@ export	_Thipx_ThunkData32
	%append $^@ export	_IPX_Initialise
	%append $^@ export	_IPX_Open_Socket95
	%append $^@ export	_IPX_Close_Socket95
	%append $^@ export	_IPX_Get_Connection_Number95
	%append $^@ export	_IPX_Send_Packet95
	%append $^@ export	_IPX_Broadcast_Packet95
	%append $^@ export	_IPX_Get_Local_Target95
	%append $^@ export	_IPX_Start_Listening95
	%append $^@ export	_IPX_Shut_Down95
	%append $^@ export	_IPX_Get_Outstanding_Buffer95